version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  tesseract:
    image: tesseractshadow/tesseract4re
    container_name: tesseract
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DMS_DIR}/consume:/input
      - ${DMS_DIR}/media:/output