version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=002
      - KEEP_APP_RUNNING=1
      - CLEAN_TEMP_DIR=1
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
      - AUTOMATED_CONVERSION_PRESET=myh265
      - AUTOMATED_CONVERSION_FORMAT=mkv
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - VNC_PASSWORD=${TORRENT_PASSWORD}
    volumes:
      - ${CONF_DIR}/handbrake/config:/config
      - ${DOWNLOAD_DIR}/completed:/watch
      - ${DOWNLOAD_DIR}/handbrake_output:/output
    networks:
      - traefik_proxy
    expose:
      - 5800
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake.entrypoints=https"
      - "traefik.http.routers.handbrake.rule=Host(`handbrake.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.handbrake.tls=true"
      - "traefik.http.routers.handbrake.middlewares=chain-no-auth@file"
      - "traefik.http.routers.handbrake.service=handbrake"
      - "traefik.http.services.handbrake.loadbalancer.server.port=5800"