version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  handbrake:
    image: jlesage/handbrake:v23.06.1
    container_name: handbrake
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/handbrake/data:/config
    networks:
      - traefik_proxy
    expose:
      - 5800
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake.entrypoints=https"
      - "traefik.http.routers.handbrake.rule=Host(`handbrake.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.handbrake.tls=true"
      - "traefik.http.routers.handbrake.middlewares=chain-oauth@file"
      - "traefik.http.routers.handbrake.service=handbrake"
      - "traefik.http.services.handbrake.loadbalancer.server.port=5800"
