version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  # unifi:
  #   container_name: unifi
  #   image: ghcr.io/linuxserver/unifi-controller
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - MEM_LIMIT=1024M
  #     - MEM_STARTUP=1024M
  #     - RUNAS_UID0="false"
  #     - BIND_PRIV="false"
  #   volumes:
  #     - ${CONF_DIR}/unifi/config:/config
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - traefik_proxy
  #   security_opt:
  #     - no-new-privileges:true
  #   ports:
  #     - "8080:8080"
  #     - "8443:8443"
  #     - "3478:3478/udp"
  #     - "10001:10001/udp"
  #     - "6789:6789"
  #     #- "8081:8081"
  #     #- "8843:8843"
  #     #- "8880:8880"

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONGO_USER=${MONGO_UNIFI_USER}
      - MONGO_PASS=${MONGO_UNIFI_PASSWORD}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_UNIFI_DB}
    volumes:
      - ${CONF_DIR}/unifi/config:/config
    networks:
      - traefik_proxy
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=https"
      - "traefik.http.routers.unifi.rule=Host(`unifi.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.unifi.tls=true"
      - "traefik.http.routers.unifi.middlewares=chain-unifi@file"
      - "traefik.http.routers.unifi.service=unifi"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
