services:
  sonarr-exportarr:
    container_name: sonarr-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0.1
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    command: ["sonarr"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=$SONARR_API_KEY
    ports:
      - 9707:9707

  radarr-exportarr:
    container_name: radarr-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0.1
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    command: ["radarr"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PORT=9708
      - URL=http://radarr:7878
      - APIKEY=$RADARR_API_KEY
  
  prowlarr-exportarr:
    container_name: prowlarr-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0.1
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    command: ["prowlarr"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PORT=9710
      - URL=http://prowlarr:9696
      - APIKEY=$PROWLARR_API_KEY

  sabnzbd-exportarr:
    container_name: sabnzbd-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0.1
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    command: ["sabnzbd"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PORT=9711
      - URL=http://sabnzbd:8080
      - APIKEY=$SABNZBD_API_KEY
