version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK_SET=002
      - serverIP=tdarr
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - ${CONF_DIR}/tdarr/config:/app/configs
      - ${CONF_DIR}/tdarr/logs:/app/logs
      - ${CONF_DIR}/tdarr/server:/app/server
      - ${CONF_DIR}/tdarr/transcode_cache:/temp
      - ${MEDIA_DIR}:/media
    networks:
      - traefik_proxy
    ports:
      - 8266:8266
      - 8265:8265
      - 8267:8267
    expose:
      - 8265
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.entrypoints=https"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.tdarr.tls=true"
      - "traefik.http.routers.tdarr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.tdarr.service=tdarr"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"

  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK_SET=002
      - nodeID=MainNode
      - nodeIP=tdarr-node
      - nodePort=8267
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - ${CONF_DIR}/tdarr/config:/app/configs
      - ${CONF_DIR}/tdarr/logs:/app/logs
      - ${CONF_DIR}/tdarr/transcode_cache:/temp
      - ${MEDIA_DIR}:/media
    networks:
      - traefik_proxy
    devices:
      - /dev/dri:/dev/dri