version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/sonarr/config:/config
      - ${MEDIA_DIR}/TV:/tv
      - ${MEDIA_DIR}/Series:/series
      - ${DOWNLOAD_DIR}:/downloads
      - ${DOWNLOAD_DIR}:/data
    expose:
      - 8989