version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  tautulli:
    image: tautulli/tautulli:nightly
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/tautulli/config:/config
      - ${CONF_DIR}/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    networks:
      - traefik_proxy
    expose:
    - 8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.xteve-rtr.tls=true"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"