version: "3.7"
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/sabnzbd/config:/config
      - ${DOWNLOAD_DIR}:/downloads
    expose:
      - 8080