version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  jackett:
    image: linuxserver/jackett:development
    container_name: jackett
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/jackett/config:/config
      - ${CONF_DIR}/jackett/blackhole:/downloads
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik_proxy
    expose:
      - 9117
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett-rtr.entrypoints=https"
      - "traefik.http.routers.jackett-rtr.rule=Host(`jackett.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.jackett.middlewares=chain-no-auth@file"
      - "traefik.http.routers.jackett-rtr.service=jackett-svc"
      - "traefik.http.services.jackett-svc.loadbalancer.server.port=9117"
