version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK=002
      - KEEP_APP_RUNNING=1
      - CLEAN_TEMP_DIR=1
      - AUTOMATED_CONVERSION_KEEP_SOURCE=1
      - VNC_PASSWORD=${TORRENT_PASSWORD}
    volumes:
      - ${CONF_DIR}/handbrake/config:/config
      - ${DOWNLOAD_DIR}/completed:/watch
      - ${DOWNLOAD_DIR}/handbrake_output:/output
    networks:
      - traefik_proxy
    expose:
      - 5800
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake-rtr.entrypoints=https"
      - "traefik.http.routers.handbrake-rtr.rule=Host(`handbrake.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.handbrake-rtr.tls=true"
      - "traefik.http.routers.handbrake-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.handbrake-rtr.service=handbrake-svc"
      - "traefik.http.services.handbrake-svc.loadbalancer.server.port=5800"