version: "3.7"
services:
  ombi:
    image: linuxserver/ombi:v4-preview
    container_name: ombi
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/ombi/config:/config
    expose:
      - 3579
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
    #   - diun.enable=true
    #   - diun.watch_repo=true