version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/overseerr/config:/config
    networks:
      - traefik_proxy
    expose:
      - 5055
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.$MEELSNET_DOMAIN`) || Host(`request.$MEELSNET_DOMAIN`) || Host(`ombi.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"
      - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"