version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/radarr/config:/config
      - ${MEDIA_DIR}/Movies:/movie
      - ${MEDIA_DIR}/Animation:/animation
      - ${DOWNLOAD_DIR}:/downloads
      - ${DOWNLOAD_DIR}:/data
    networks:
      - traefik_proxy
    expose:
      - 7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-rtr.entrypoints=https"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`radarr.$MEELSNET_DOMAIN`) || Host(`movies.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.sonarr-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=7878"