version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  prowlarr:
    image: linuxserver/prowlarr:nightly
    container_name: prowlarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/prowlarr/config:/config
      - ${DOWNLOAD_DIR}:/data
      - ${DOWNLOAD_DIR}:/downloads
    networks:
      - traefik_proxy
    expose:
      - 9696
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-rtr.entrypoints=https"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.$MEELSNET_DOMAIN`) || Host(`indexer.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.prowlarr-rtr.tls=true"
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696"