version: "3.7"
services:
  # Plex monitor
  tautulli:
    image: linuxserver/tautulli:develop
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/tautulli/config:/config
      - ${CONF_DIR}/tautulli/logs:/logs
      - ${CONF_DIR}/plex/config:/plex/config:ro
    expose:
    - 8181
    # labels:
    # - com.centurylinklabs.watchtower.enable=true
    # - diun.enable=true
    # - diun.watch_repo=true