version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/sonarr/config:/config
      - ${MEDIA_DIR}/TV:/tv
      - ${MEDIA_DIR}/Series:/series
      - ${DOWNLOAD_DIR}:/data
      - ${DOWNLOAD_DIR}:/downloads
    networks:
      - traefik_proxy
    expose:
      - 8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-rtr.entrypoints=https"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.$MEELSNET_DOMAIN`) || Host(`series.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.sonarr-rtr.tls=true"
      - "traefik.http.routers.sonarr-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"