version: "3.7"
services:
  jackett:
    image: linuxserver/jackett:development
    container_name: jackett
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/jackett/config:/config
      - ${CONF_DIR}/jackett/blackhole:/downloads
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9117
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
    #   - diun.enable=true
    #   - diun.watch_repo=true