##### NETWORKS #####
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/16

##### SECRETS #####
secrets:
  basic_auth_credentials:
    file: $DOCKER_DIR/secrets/basic_auth_credentials
  cf_dns_api_token:
    file: $DOCKER_DIR/secrets/cf_dns_api_token
  oauth_secrets:
    file: $DOCKER_DIR/secrets/oauth_secrets

include:
  ##### SERVICES #####
  # Reverse proxy
  - compose/reverse-proxy/traefik.yml
  - compose/reverse-proxy/oauth.yml
    
  # Media containers
  
  # Game containers

  # Other containers
