version: "3.7"
services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/ombi/config:/config
    expose:
      - 3579