services:
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:2.2.0
    restart: unless-stopped
    profiles: ["reverse-proxy", "all"]
    networks:
      - t3_proxy
    secrets:
      - source: oauth_secrets
        target: /config
    environment:
      - CONFIG=/config
      - COOKIE_DOMAIN=$MEELSNET_DOMAIN
      - INSECURE_COOKIE=false
      - AUTH_HOST=oauth.$MEELSNET_DOMAIN
      - URL_PATH=/_oauth
      - LOG_LEVEL=warn
      - LOG_FORMAT=text
      - LIFETIME=86400
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=google
    expose:
      - 4181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth-rtr.tls=true"
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.$DOMAINNAME_1`)"
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"