version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  # Media stream service
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: unless-stopped
    hostname: plex
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    volumes:
      - ${CONF_DIR}/plex/config:/config
      - ${CONF_DIR}/plex/data:/data
      - ${CONF_DIR}/plex/deb:/debi
      - ${CONF_DIR}/plex/dvr:/dvr
      - ${CONF_DIR}/plex/transcode:/transcode
      - ${MEDIA_DIR}/TV:/data/tv
      - ${MEDIA_DIR}/Movies:/data/movies
      - ${MEDIA_DIR}/Series:/data/series
      - ${MEDIA_DIR}/Animation:/data/animation
    networks:
      - traefik_proxy
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 32469:32469
      - 3005:3005
      - 8324:8324
      - 32469:32469/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    expose:
      - 32400
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.rule=Host(`plex.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.middlewares=chain-no-auth@file"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    devices:
      - /dev/dri:/dev/dri