version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    restart: unless-stopped
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/maintainerr/config:/config
      - ${MEDIA_DIR}:/opt/data
    networks:
      - traefik_proxy
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintainerr.entrypoints=https"
      - "traefik.http.routers.maintainerr.rule=Host(`maintainerr.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.maintainerr.tls=true"
      - "traefik.http.routers.maintainerr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.maintainerr.service=maintainerr"
      - "traefik.http.services.maintainerr.loadbalancer.server.port=80"
